# example values

indexing-settings:
  sites:
    - url: https://dombulgakova.ru/
      name: dombulgakova.ru
    - url: https://kulinarnia.ru/
      name: kulinarnia.ru/
    - url: https://www.svetlovka.ru/
      name: svetlovka.ru

jsoup-connection-settings:
  userAgent: SiteSearchBot
  referrer: http://www.yandex.ru

server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        enable_lazy_Load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
